-- Imported from Slamrish/ModernGuides-Source (RXP format)
-- Classic-compatible conversion for VanillaGuide-Enhanced
-- English only

if GetLocale() ~= "enUS" and GetLocale() ~= "enGB" then return end

Table_010_RXP_Hardcore_LochModan_18to19 = {
    [1023] = {
        title = "18-19 Loch Modan",
        items = {
            [1] = { str = "18-19 Loch Modan" },
            [2] = { str = "Go to #COORD[8,56]# in Wetlands. Talk to Dewin Shimmerdawn Buy as many Healing Potions that are available This is a limited supply item. Skip this step if Dewin Shimmerdawn doesn't have any Target #NPCDewin Shimmerdawn#.", x = 8, y = 56, zone = "Wetlands" },
            [3] = { str = "Go to #COORD[10,56]# in Wetlands. Go to #COORD[10,57]# in Wetlands. Go to #COORD[11,57]# in Wetlands. Go to #COORD[11,57]# in Wetlands. Talk to Neal Allen Buy a Bronze Tube This is a limited supply item. Skip this step if Neal Allen doesn't have one Target #NPCNeal Allen#.", x = 10, y = 56, zone = "Wetlands" },
            [4] = { str = "Go to #COORD[11,58]# in Wetlands. Talk to Edwina Monzor Buy a Medium Quiver and Sharp Arrows Collect #ITEMMedium Quiver (1)#. Collect #ITEMSharp Arrow (1800)#. Target #NPCEdwina Monzor#. (Hunter only)", x = 11, y = 58, zone = "Wetlands" },
            [5] = { str = "Go to #COORD[10,61]# in Wetlands. Go to #COORD[10,60]# in Wetlands. Talk to Samor Festivus upstairs Buy as many Healing Potions that are available This is a limited supply item. Skip this step if Samor Festivus doesn't have any Target #NPCSamor Festivus#.", x = 10, y = 61, zone = "Wetlands" },
            [6] = { str = "Go to #COORD[9,60]# in Wetlands. Talk to Shellei Fly to Loch Modan Target #NPCShellei Brondir#.", x = 9, y = 60, zone = "Wetlands" },
            [7] = { str = "Go to #COORD[35,44]# in Loch Modan. Go to #COORD[35,43]# in Loch Modan. Talk to Magistrate Bluntnose Accept #GETMercenaries#. Target #NPCMagistrate Bluntnose#.", x = 35, y = 44, zone = "Loch Modan" },
            [8] = { str = "Go to #COORD[37,48]# in Loch Modan. Go to #COORD[37,47]# in Loch Modan. Talk to Jern Hornhelm Accept #GETIronband's Excavation#. Target #NPCJern Hornhelm#.", x = 37, y = 48, zone = "Loch Modan" },
            [9] = { str = "Go to #COORD[24,18]# in Loch Modan.", x = 24, y = 18, zone = "Loch Modan" },
            [10] = { str = "Go to #COORD[24,18]# in Loch Modan. Go to #COORD[25,18]# in Loch Modan. Talk to Mountaineer Stormpike Turn in #INStormpike's Delivery#. Accept #GETFilthy Paws#. Target #NPCMountaineer Stormpike#.", x = 24, y = 18, zone = "Loch Modan" },
            [11] = { str = "Go to #COORD[36,19]# in Loch Modan.", x = 36, y = 19, zone = "Loch Modan" },
            [12] = { str = "Go to #COORD[36,23]# in Loch Modan. Open the Miners' League Crates. Loot them for the Miners' Gear The Miners' League Crates can be found all throughout the Mine #DOMiners' Gear (4)#.", x = 36, y = 23, zone = "Loch Modan" },
            [13] = { str = "Go to #COORD[24,18]# in Loch Modan. Go to #COORD[25,18]# in Loch Modan. Talk to Mountaineer Stormpike Turn in #INFilthy Paws#. Target #NPCMountaineer Stormpike#.", x = 24, y = 18, zone = "Loch Modan" },
            [14] = { str = "Go to #COORD[43,10]# in Loch Modan.", x = 43, y = 10, zone = "Loch Modan" },
            [15] = { str = "Go to #COORD[46,14]# in Loch Modan. Talk to Chief Engineer Hinderweir VII Accept #GETA Dark Threat Looms#. Target #NPCChief Engineer Hinderweir VII#.", x = 46, y = 14, zone = "Loch Modan" },
            [16] = { str = "Go to #COORD[56,13]# in Loch Modan. Click the Suspicious Barrel Turn in #INA Dark Threat Looms#. Accept #GETA Dark Threat Looms#.", x = 56, y = 13, zone = "Loch Modan" },
            [17] = { str = "Go to #COORD[46,14]# in Loch Modan. Talk to Chief Engineer Hinderweir VII Turn in #INA Dark Threat Looms#. Target #NPCChief Engineer Hinderweir VII#.", x = 46, y = 14, zone = "Loch Modan" },
            [18] = { str = "Be careful not to run into the Horde Runners! It's an elite pack of 2 Orcs and a Tauren who patrol the east side of The Loch (the line on your map)" },
            [19] = { str = "Go to #COORD[83,59]# in Loch Modan. Go to #COORD[83,63]# in Loch Modan.", x = 83, y = 59, zone = "Loch Modan" },
            [20] = { str = "Talk to Daryl the Youngling Accept #GETA Hunter's Boast#. Go to #COORD[83,65]# in Loch Modan. Target #NPCDaryl the Youngling#.", x = 83, y = 65, zone = "Loch Modan" },
            [21] = { str = "Go to #COORD[82,63]# in Loch Modan. Talk to Claude Erksine Train your pet spells Target #NPCClaude Erksine#. (Hunter only)", x = 82, y = 63, zone = "Loch Modan" },
            [22] = { str = "Go to #COORD[82,62]# in Loch Modan. Talk to Dargh Trueaim Train your class spells Target #NPCDargh Trueaim#. (Hunter only)", x = 82, y = 62, zone = "Loch Modan" },
            [23] = { str = "Talk to Marek Ironheart Accept #GETCrocolisk Hunting#. Go to #COORD[82,62]# in Loch Modan. Target #NPCMarek Ironheart#.", x = 82, y = 62, zone = "Loch Modan" },
            [24] = { str = "Go to #COORD[80,64]# in Loch Modan. Go to #COORD[77,76]# in Loch Modan. Go to #COORD[71,73]# in Loch Modan. Go to #COORD[77,62]# in Loch Modan. Go to #COORD[76,56]# in Loch Modan. Go to #COORD[80,64]# in Loch Modan. Go to #COORD[77,76]# in Loch Modan. Go to #COORD[71,73]# in Loch Modan. Go to #COORD[77,62]# in Loch Modan. Go to #COORD[76,56]# in Loch Modan. Go to #COORD[80,64]# in Loch Modan. Kill Mountain Buzzards You must complete this quest and return to Daryl the Youngling within 15 minutes. If you fail the quest, abandon it and pick it up again #DOMountain Buzzard slain (6)#. Kill #NPCMountain Buzzard#.", x = 80, y = 64, zone = "Loch Modan" },
            [25] = { str = "Go to #COORD[83,59]# in Loch Modan. Go to #COORD[83,63]# in Loch Modan.", x = 83, y = 59, zone = "Loch Modan" },
            [26] = { str = "Talk to Daryl the Youngling Go to #COORD[83,65]# in Loch Modan. Turn in #INA Hunter's Boast#. Accept #GETA Hunter's Challenge#. Target #NPCDaryl the Youngling#.", x = 83, y = 65, zone = "Loch Modan" },
            [27] = { str = "Go to #COORD[75,50]# in Loch Modan. Go to #COORD[76,43]# in Loch Modan. Go to #COORD[71,39]# in Loch Modan. Go to #COORD[66,42]# in Loch Modan. Go to #COORD[62,32]# in Loch Modan. Go to #COORD[73,40]# in Loch Modan. Go to #COORD[74,52]# in Loch Modan. Go to #COORD[69,39]# in Loch Modan. Kill Elder Mountain Boars You must complete this quest and return to Daryl the Youngling with 12 minutes. If you fail the quest, abandon it and pick it up again #DOElder Mountain Boar slain (5)#. Kill #NPCElder Mountain Boar#.", x = 75, y = 50, zone = "Loch Modan" },
            [28] = { str = "Go to #COORD[83,59]# in Loch Modan. Go to #COORD[83,63]# in Loch Modan.", x = 83, y = 59, zone = "Loch Modan" },
            [29] = { str = "Talk to Daryl the Youngling Go to #COORD[83,65]# in Loch Modan. Turn in #INA Hunter's Challenge#. Target #NPCDaryl the Youngling#.", x = 83, y = 65, zone = "Loch Modan" },
            [30] = { str = "Talk to Vyrin Swiftwind Go to #COORD[82,64]# in Loch Modan. Accept #GETVyrin's Revenge#. Target #NPCVyrin Swiftwind#.", x = 82, y = 64, zone = "Loch Modan" },
            [31] = { str = "Be careful not to run into the Horde Runners! It's an elite pack of 2 Orcs and a Tauren who patrol the east side of The Loch (the line on your map)" },
            [32] = { str = "Go to #COORD[55,38]# in Loch Modan.", x = 55, y = 38, zone = "Loch Modan" },
            [33] = { str = "Go to #COORD[59,38]# in Loch Modan. Go to #COORD[55,40]# in Loch Modan. Go to #COORD[54,36]# in Loch Modan. Go to #COORD[55,38]# in Loch Modan. Kill Loch Crocolisks. Loot them for their Meat and Skin #DOCrocolisk Meat (5)#. #DOCrocolisk Skin (6)#. Kill #NPCLoch Crocolisk#.", x = 59, y = 38, zone = "Loch Modan" },
            [34] = { str = "Be careful not to run into the Horde Runners! It's an elite pack of 2 Orcs and a Tauren who patrol the east side of The Loch (the line on your map)" },
            [35] = { str = "Go to #COORD[65,67]# in Loch Modan.", x = 65, y = 67, zone = "Loch Modan" },
            [36] = { str = "Go to #COORD[65,67]# in Loch Modan. Talk to Magmar Fellhew Turn in #INIronband's Excavation#. Accept #GETGathering Idols#. Target #NPCMagmar Fellhew#.", x = 65, y = 67, zone = "Loch Modan" },
            [37] = { str = "Go to #COORD[66,66]# in Loch Modan. Talk to Prospector Ironband Accept #GETExcavation Progress Report#. Target #NPCProspector Ironband#.", x = 66, y = 66, zone = "Loch Modan" },
            [38] = { str = "Go to #COORD[67,60]# in Loch Modan. Go to #COORD[71,61]# in Loch Modan. Go to #COORD[73,62]# in Loch Modan. Go to #COORD[71,69]# in Loch Modan. Go to #COORD[70,63]# in Loch Modan. Kill Stonesplinter Diggers, Stonesplinter Geomancers and Berserk Troggs. Loot them for their Idols Kill #NPCStonesplinter Digger#. Kill #NPCStonesplinter Geomancer#. Kill #NPCBerserk Trogg#.", x = 67, y = 60, zone = "Loch Modan" },
            [39] = { str = "Go to #COORD[65,67]# in Loch Modan. Talk to Magmar Fellhew Turn in #INGathering Idols#. Target #NPCMagmar Fellhew#.", x = 65, y = 67, zone = "Loch Modan" },
            [40] = { str = "Go to #COORD[41,64]# in Loch Modan.", x = 41, y = 64, zone = "Loch Modan" },
            [41] = { str = "Go to #COORD[39,66]# in Loch Modan. Go to #COORD[41,63]# in Loch Modan. Go to #COORD[40,62]# in Loch Modan. Go to #COORD[38,63]# in Loch Modan. Go to #COORD[37,61]# in Loch Modan. Kill Ol' Sooty. Loot him for his Head Ol' Sooty is not always inside his cave, and may patrol down the path to the lower grounds Ol' Sooty is a level 20 Elite #DOOl' Sooty's Head (1)#.", x = 39, y = 66, zone = "Loch Modan" },
            [42] = { str = "Go to #COORD[83,59]# in Loch Modan. Go to #COORD[83,63]# in Loch Modan.", x = 83, y = 59, zone = "Loch Modan" },
            [43] = { str = "Go to #COORD[82,62]# in Loch Modan. Talk to Marek Ironheart Turn in #INCrocolisk Hunting#. Target #NPCMarek Ironheart#.", x = 82, y = 62, zone = "Loch Modan" },
            [44] = { str = "Talk to Daryl the Youngling Go to #COORD[83,65]# in Loch Modan. Turn in #INVyrin's Revenge#. Target #NPCDaryl the Youngling#.", x = 83, y = 65, zone = "Loch Modan" },
            [45] = { str = "Talk to Daryl the Youngling Go to #COORD[83,65]# in Loch Modan. Accept #GETVyrin's Revenge#. Target #NPCDaryl the Youngling#.", x = 83, y = 65, zone = "Loch Modan" },
            [46] = { str = "Talk to Vyrin Swiftwind Go to #COORD[82,64]# in Loch Modan. Turn in #INVyrin's Revenge#. Target #NPCVyrin Swiftwind#.", x = 82, y = 64, zone = "Loch Modan" },
            [47] = { str = "Abandon Vyrin's Revenge" },
            [48] = { str = "Go to #COORD[74,30]# in Loch Modan.", x = 74, y = 30, zone = "Loch Modan" },
            [49] = { str = "Kill Mo'grosh Ogres, Mo'grosh Enforcers and Mo'grosh Brutes Mo'grosh Brutes are only found inside the Caves. It is recommended you don't enter the northeastern cave, and just kill them in the 2 other Mini-Caves #DOMo'grosh Ogre slain (4)#. Kill #NPCMo'grosh Ogre#. Go to #COORD[74,30]# in Loch Modan. Go to #COORD[74,25]# in Loch Modan. Go to #COORD[74,20]# in Loch Modan. Go to #COORD[69,21]# in Loch Modan. Go to #COORD[69,28]# in Loch Modan. Go to #COORD[71,24]# in Loch Modan. #DOMo'grosh Enforcer slain (4)#. Kill #NPCMo'grosh Enforcer#. Go to #COORD[74,30]# in Loch Modan. Go to #COORD[74,25]# in Loch Modan. Go to #COORD[74,20]# in Loch Modan. Go to #COORD[69,21]# in Loch Modan. Go to #COORD[69,28]# in Loch Modan. Go to #COORD[71,24]# in Loch Modan. #DOMo'grosh Brute slain (4)#. Go to #COORD[69,19]# in Loch Modan. Go to #COORD[75,25]# in Loch Modan. Go to #COORD[69,19]# in Loch Modan. Go to #COORD[75,25]# in Loch Modan. Kill #NPCMo'grosh Brute#.", x = 74, y = 30, zone = "Loch Modan" },
            [50] = { str = "Be careful not to run into the Horde Runners! It's an elite pack of 2 Orcs and a Tauren who patrol the east side of The Loch (the line on your map)" },
            [51] = { str = "Go to #COORD[37,46]# in Loch Modan.", x = 37, y = 46, zone = "Loch Modan" },
            [52] = { str = "Go to #COORD[37,48]# in Loch Modan. Go to #COORD[37,47]# in Loch Modan. Talk to Jern Hornhelm Turn in #INExcavation Progress Report#. Accept #GETReport to Ironforge#. Target #NPCJern Hornhelm#.", x = 37, y = 48, zone = "Loch Modan" },
            [53] = { str = "Go to #COORD[35,44]# in Loch Modan. Go to #COORD[35,43]# in Loch Modan. Talk to Magistrate Bluntnose Turn in #INMercenaries#. Target #NPCMagistrate Bluntnose#.", x = 35, y = 44, zone = "Loch Modan" },
            [54] = { str = "Abandon Mercenaries" },
            [55] = { str = "Go to #COORD[34,51]# in Loch Modan. Talk to Thorgrum Fly to Ironforge Target #NPCThorgrum Borrelson#.", x = 34, y = 51, zone = "Loch Modan" },
            [56] = { str = "Go to #COORD[75,12]# in Ironforge. Talk to Prospector Stormpike Turn in #INReport to Ironforge#. Target #NPCProspector Stormpike#.", x = 75, y = 12, zone = "Ironforge" },
            [57] = { str = "Go to #COORD[36,60]# in Ironforge. Talk to Bailey Stonemantle Deposit the following items into your bank: Elixir of Water Breathing (If you have them) Target #NPCBailey Stonemantle#.", x = 36, y = 60, zone = "Ironforge" },
            [58] = { str = "Go to #COORD[68,42]# in Ironforge. Talk to Gearcutter Cogspinner Buy a Bronze Tube This is a limited supply item. Skip this step if Gearcutter Cogspinner doesn't have one Target #NPCGearcutter Cogspinner#.", x = 68, y = 42, zone = "Ironforge" },
            [59] = { str = "Go to #COORD[78,52]# in Ironforge. Enter the Deeprun Tram. Take the tram to Stormwind Level your First Aid and Cooking if needed while waiting for the tram You will need your First Aid to be 80 for a quest at level 24", x = 78, y = 52, zone = "Ironforge" },
        }
    },
}
